---
# homebrew を最新版にする
- name: common | brew update
  homebrew: update_homebrew=yes

# 全モジュールを upgrade する
- name: common | brew upgrade all
  homebrew: upgrade_all=yes

- name: tap
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - peco/peco
    - motemen/ghq
    - neovim/neovim
# - name: update
#   homebrew: update_homebrew=yes
# - name: upgrade
#   homebrew: upgrade_all=yes

- name: Install vim with Lua and Python3
  tags:
    - work
  homebrew: name=vim state=latest install_options=with-lua,with-python3,override-system-vi

- name: Install libraries with homebrew
  tags:
    - work
  homebrew: name={{ item }} state=latest
  with_items:
    # database
    - mysql

    # git
    - git
    - tig
    # - git-flow

    # shells
    - bash
    - zsh
    - fish

    # - neovim

    # go
    - go

    # ruby
    - rbenv
    - ruby-build

    # node
    - node
    - npm

    # miscellaneous
    - tmux
    # - screen

    - ansible
    - boot2docker
    - docker

    #
    - mogenerator

    # utils
    - wget
    - tree
    - ack
    - ag
    - nkf
    - gnu-sed
    - colordiff
    - z
    - peco
    - ghq
    - jq
    - httpie
