---
# homebrew を最新版にする
- name: common | brew update
  homebrew: update_homebrew=yes

# 全モジュールを upgrade する
- name: common | brew upgrade all
  homebrew: upgrade_all=yes

- name: tap
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - peco/peco
    - motemen/ghq
    - neovim/neovim
    #- sanemat/font
    - homebrew/services
# - name: update
#   homebrew: update_homebrew=yes
# - name: upgrade
#   homebrew: upgrade_all=yes

- name: Install vim with Lua and Python3
  tags:
    - work
  homebrew: name=vim state=latest install_options=with-lua,with-python3,override-system-vi

- name: Install libraries with homebrew
  tags:
    - work
  homebrew: name={{ item }} state=latest
  with_items:
    - vim --withlua
    # database
    - mysql

    # git
    - git
    - tig
    # - git-flow

    # shells
    - bash
    - zsh
    - fish

    # - neovim

    # go
    - go

    # ruby
    - rbenv
    - ruby-build

    # node
    - node
    - npm

    # miscellaneous
    - tmux
    # - screen

    - ansible

    #
    - mogenerator

    # font
    #- ricty

    # utils
    - wget
    - tree
    - ack
    - ag
    - nkf
    - gnu-sed
    - colordiff
    - z
    - thefuck
    - peco
    - ghq
    - jq
    - httpie
    - awscli
    - git-secrets
    - gibo
    - ipcalc
    - teensy_loader_cli
    - autossh
    - textql
    - cloc

- name: clone ricty fonts
  shell: ghq get git@github.com:mzyy94/RictyDiminished-for-Powerline.git
  tags:
    - work
- name: install ricty fonts
  copy: src=~/.ghq/github.com/mzyy94/RictyDiminished-for-Powerline/{{ item }} dest=~/Library/Fonts/
  with_items:
    - RictyDiminished-Bold-Powerline.ttf
    - RictyDiminished-Regular-Powerline.ttf
    - RictyDiminishedDiscord-Bold-Powerline.ttf
    - RictyDiminishedDiscord-Regular-Powerline.ttf
  tags:
    - work

- command: fc-cache -vf
  tags:
    - work
