---
# homebrew を最新版にする
- name: common | brew update
  homebrew: update_homebrew=yes

# 全モジュールを upgrade する
- name: common | brew upgrade all
  homebrew: upgrade_all=yes

- name: tap
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/services
    - tkengo/highway
    - fisherman/tap
    - minerva1129/homebrew-anyenv
    - mackerelio/mackerel-agent
    # - peco/peco
    #- motemen/ghq
    #- neovim/neovim
    #- homebrew/php/php-cs-fixer
# - name: update
#   homebrew: update_homebrew=yes
# - name: upgrade
#   homebrew: upgrade_all=yes

- name: Install vim with Lua and Python3
  tags:
    - work
    - home
  homebrew: name=vim state=latest options=with-lua,with-python3,with-python,with-override-system-vi
