---
- name: tap
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/cask-fonts
    - sanemat/font

- name: Install xquartz
  tags:
    - work
    - home
  homebrew_cask: name=xquartz state=present

- name: Install Fira Code
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-fira-code state=present
- name: Install Fira Code Nerd Font
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-fira-code-nerd-font state=present
- name: Install Fira Mono for Powerline
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-fira-mono-for-powerline state=present

- name: Install Myrica
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-myrica state=present

- name: Install Cica
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-cica state=present

- name: Install Noto Nerd Font
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-noto-nerd-font state=present
- name: Install Noto Mono for Powerline
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-noto-mono-for-powerline state=present

- name: Install Ubuntu Nerd Font
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-ubuntu-nerd-font state=present
- name: Install Ubuntu Mono Derivative Powerline
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-ubuntu-mono-derivative-powerline state=present

- name: Install Ricty Diminished
  tags:
    - work
    - home
  homebrew_cask: name=homebrew/cask-fonts/font-ricty-diminished state=present

- name: Install Source Han Code JP
  tags:
    - work
    - home
  homebrew_cask: name=font-source-han-code-jp state=present

- name: Install M+
  tags:
    - work
    - home
  homebrew_cask: name=font-mplus state=present
- name: Install M+ Nerd Font
  tags:
    - work
    - home
  homebrew_cask: name=font-mplus state=present
  homebrew_cask: name=font-mplus-nerd-font state=present

# - name: Install Ricty
#   tags:
#     - work
#     - home
#   homebrew: name=ricty state=present options=with-powerline
#
# - name: Copy font file
#   shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
#   args:
#     creates: ~/Library/Fonts/Ricty-Bold.ttf
# - name: fc-cache
#   shell: fc-cache -vf
#
