---
- name: Install libraries with homebrew
  tags:
    - work
  homebrew: name={{ item }} state=latest
  with_items:
    - mas
    # database
    - mysql

    # git
    - git
    - tig
    - hub
    - git-secrets
    - gibo
    # - git-flow

    # shells
    - bash
    - fish
    - fisherman

      #- anyenv --HEAD
    # - neovim

    # go
    - go
    - glide

    # php
    # - homebrew/php/php-cs-fixer
    # - homebrew/php/composer
    # - phpmd
    # - php-code-sniffer

    # ruby
    - rbenv
    - ruby-build

    # node
    - node
    - npm

    # miscellaneous
    - byobu
    - tmux
    # - screen

    - ansible

    #
    # - mogenerator

    # utils
    - wget
    - curl
    - httpie
    - jq

    - tree

    - ack
    - highway
    - ag

    - nkf
    - gnu-sed
    - z
    - thefuck
    - peco
    - ghq

    - awscli
    - amazon-ecs-cli
      #- stormssh
    - ipcalc
      #- teensy_loader_cli
    - autossh
    - textql
    - cloc
    - ctags

    - grc
    - colordiff

      #- heroku
    - mkr
    - carthage
