[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1 # on insert

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_i = 1

# Ruby
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

# Perl
[[plugins]]
repo = 'perl-mauke.vim'
on_ft = ['perl']

# JavaScript
[[plugins]]
repo = 'bigfish/vim-js-beautify'
on_ft = ['javascript']

[[plugins]]
repo = 'JavaScript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'jQuery'
on_ft = ['javascript']

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

# golang
[[plugins]]
repo  = 'vim-jp/vim-go-extra'
on_ft = ['go']

# python
[[plugins]]
repo  = 'yuroyoro/vim-python'
on_ft = ['python']

# markdown
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

# Objective-C
# 'msanders/cocoa.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'
on_ft = ['go']

[[plugins]]
repo  = 'avakhov/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo  = 'vim-scripts/smarty-syntax'
on_ft = ['smarty']

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'nginx.vim'
on_ft = ['nginx']
