[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1 # on insert

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

# Ruby
[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

# Perl
[[plugins]]
repo = 'vim-scripts/perl-mauke.vim'
on_ft = ['perl']

# JavaScript
[[plugins]]
repo = 'bigfish/vim-js-beautify'
on_ft = ['javascript']

[[plugins]]
repo = 'vim-scripts/JavaScript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'vim-scripts/jQuery'
on_ft = ['javascript']

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

# golang
[[plugins]]
repo  = 'vim-jp/vim-go-extra'
on_ft = ['go']

# markdown
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']

# Objective-C
# 'msanders/cocoa.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_map = '<Plug>'
on_ft = ['ruby']

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'
on_ft = ['go']

[[plugins]]
repo  = 'avakhov/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo  = 'vim-scripts/smarty-syntax'
on_ft = ['smarty']

#[[plugins]]
#repo  = 'mattn/emmet-vim'
#on_ft = ['html']

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = ['nginx']

# fish
[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']

# pub / jade
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

# [[plugins]]
# repo = 'python-mode/python-mode'
# on_ft = ['python']

# [[plugins]]
# repo = 'tmhedberg/SimpylFold'
# on_ft = ['python']

#[[plugins]]
#repo = 'Valloric/YouCompleteMe'
#on_ft = ['python']

#[[plugins]]
#repo = 'mitsuhiko/vim-jinja'
#on_ft = [['python', 'jinja']]

#[[plugins]]
#repo = 'hynek/vim-python-pep8-indent'
#on_i = 1
#on_ft = 'python'

#[[plugins]]
#repo = 'vim-scripts/python.vim--Vasiliev'
#on_ft = [['python', 'django']]
