[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
# Ctrl-b / Ctrl-f
repo = 'Smooth-Scroll'

# Yank
[[plugins]]
# super yank
repo = 'yanktmp.vim'

[[plugins]]
# ctrl-p continuously
repo = 'LeafCage/yankround.vim'

[[plugins]]
# ,cc to comment out, ,cu to uncomment
repo = 'scrooloose/nerdcommenter'

[[plugins]]
# ds' = delete sorrounding ' / S' = sorround selected text with ' / change sorrounding quote char
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides.git'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
# ,,sa = find a
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

# [[plugins]]
# repo = 'errormarker.vim'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = [
  'osyo-manga/shabadou.vim',
  'thinca/vim-quickrun',
  'Shougo/vimproc',
  'cohama/vim-hier',
  'dannyob/quickfixstatus',
]

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'rking/ag.vim'

# filer
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'justinmk/vim-dirvish'

# Formatting
[[plugins]]
# gS(plit) / gJ(oin)
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
# :Tabularize/=
repo = 'godlygeek/tabular'

# Git
[[plugin]]
repo = 'tpope/vim-fugitive'

# colorscheme
[[plugins]]
repo = 'dracula/vim'

# Git
# 'int3/vim-extradite'
# 'gregsexton/gitv'

# 'simplefold'
# 'smartchr'
# 'mattn/zencoding-vim.git'

# 'yoppi/perl5lib'
# 'ywatase/flymake-perl.vim'
# 'kana/vim-flymake'

# 'vim-scripts/ShowMarks'
# 'vim-scripts/SearchComplete'

# Syntax checker
# [[plugins]]
# repo = 'scrooloose/syntastic'
