[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
# Ctrl-b / Ctrl-f
repo = 'Smooth-Scroll'

# Yank
[[plugins]]
# super yank
repo = 'yanktmp.vim'

[[plugins]]
# ctrl-p continuously
repo = 'LeafCage/yankround.vim'

[[plugins]]
# ,cc to comment out, ,cu to uncomment
repo = 'scrooloose/nerdcommenter'

[[plugins]]
# ds' = delete sorrounding ' / S' = sorround selected text with ' / change sorrounding quote char
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides.git'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
# ,,sa = find a
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
# :Tabularize/=
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'errormarker.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# filer
[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugin]]
repo = 'tell-k/vim-browsereload-mac'

# Git
# 'tpope/vim-fugitive'
# 'int3/vim-extradite'
# 'gregsexton/gitv'

# Subversion
# 'vim-scripts/svn-diff.vim'
#shows diff when commiting changes
# 'laurentb/vim-svndiff'
# 'vcscommand.vim'
# 'svndiff'
# 'svndiff.vim'
# 'svn-diff.vim'

# HTML::Template
# 'pbrisbin/html-template-syntax'

# 'mbadran/headlights'
# 'sjl/gundo.vim' " Graphical undo

# template
# 'qtmplsel.vim'

# 'simplefold'
# 'smartchr'
# 'mattn/zencoding-vim.git'

# 'yoppi/perl5lib'
# 'ywatase/flymake-perl.vim'
# 'kana/vim-flymake'

# 'vim-scripts/ShowMarks'
# 'vim-scripts/SearchComplete'

# Syntax checker
[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'nginx.vim'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

# colorscheme
[[plugins]]
repo = 'dracula/vim'
