---
- name: Install libraries with homebrew-cask
  homebrew_cask: name={{ item }} state=present
  tags:
    - home
  with_items:
    - google-photos-backup-and-sync
    - music-manager

    # VPN
    - tunnelbear

    - tinyumbrella
      #- bittorrent-sync
      #- gopro
    - airflow
    - arq
    - rescuetime
    - dynalist
    - kindle
    - synergy
    - notion

    # コミュニケーション
    - discord

    # サウンド
    - soundsource
    # メンテナンス
    #- magician
    #- onyx
    - monolingual
    # 動画
    - ripit
    - burn
    - handbrake
      #- fairmount
    - boxofsnoo-fairmount
    - makemkv
    # カメラ
    - canon-eos-utility
    # 配信
    - obs # broadcasting tool
    - obs-virtualcam
    - snapcamera
    - philips-hue-sync
