---
- name: Install libraries with homebrew-cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - qlcolorcode
    - qlstephen
    - qlmarkdown
    - quicklook-json
    - qlimagesize
    - webpquicklook
    - suspicious-package
    - quicklookase
    - qlvideo
