---
- name: Install Quick Look Plugins
  homebrew_cask:
    name:
      - qlcolorcode
      - qlstephen
      - qlmarkdown
      - quicklook-json
      - qlimagesize
      - webpquicklook
      - suspicious-package
      - quicklookase
      - qlvideo
