---
- name: Install libraries with homebrew-cask
  homebrew_cask: name={{ item }} state=present
  tags:
    - work
  with_items:
    - toggl
    - slack
    - docker
    - dash
    - zeplin
    - figma
    - postman
    - poedit
    - stand
    - paw
    - proxyman
    - timely
    - memory
    - github
