#update homebrew
update
#doctor

#upgrade already installed homebrew packages
upgrade

#install my standard packages
tap homebrew/versions

# Add Repository
tap caskroom/homebrew-cask
tap homebrew/binary


# Packages brew-file
install rcmdnk/file/brew-file

# Packages - Go
install go

# Packages - Base
install bash
install zsh
install zsh-completions
install zsh-syntax-highlighting

install tmux
install screen

install ack
install nkf
install gnu-sed
install wget
install tree
install libdvdcss

# Packages - git
install git
install git-flow
install tig

# Packages - Objective-C
install mogenerator
#install appledoc

# Packages - WebDev
install rbenv
install ruby-build
install node
install npm

# Packages - Editor
install vim

# Packages - Jenkins
install jenkins
install mono

# Remove outdated versions from the cellar
cleanup

