# ansible-galaxy
# Autogenerated from man page /usr/local/share/man/man1/ansible-galaxy.1
# using Deroffing man parser
complete -c ansible-galaxy -s h -l help --description '.'
complete -c ansible-galaxy -s r --description '.'
complete -c ansible-galaxy -s f -l force --description '.'
complete -c ansible-galaxy -s i -l ignore-errors --description '.'
complete -c ansible-galaxy -s n -l no-deps --description '.'
complete -c ansible-galaxy -s p -l roles-path --description '.'
complete -c ansible-galaxy -l role-file --description '.'
complete -c ansible-galaxy -l init-path --description '.'
complete -c ansible-galaxy -l offline --description '.'

