# ansible-playbook
# Autogenerated from man page /usr/local/share/man/man1/ansible-playbook.1
# using Deroffing man parser
complete -c ansible-playbook -s v -l verbose --description 'Verbose mode, more output from successful actio… [See Man Page]'
complete -c ansible-playbook -s i -l inventory --description 'The PATH to the inventory hosts file, which def… [See Man Page]'
complete -c ansible-playbook -s M -l module-path --description 'The DIRECTORY search path to load modules from.'
complete -c ansible-playbook -s e -l extra-vars --description 'Extra variables to inject into a playbook, in k… [See Man Page]'
complete -c ansible-playbook -s f -l forks --description 'Level of parallelism.'
complete -c ansible-playbook -s k -l ask-pass --description 'Prompt for the SSH password instead of assuming… [See Man Page]'
complete -c ansible-playbook -s K -l ask-sudo-pass --description 'Prompt for the password to use for playbook pla… [See Man Page]'
complete -c ansible-playbook -s U -l sudo-user --description 'Desired sudo user (default=root).'
complete -c ansible-playbook -s t -l tags --description 'Only run plays and tasks tagged with these values.'
complete -c ansible-playbook -l skip-tags --description 'Only run plays and tasks whose tags do not match these values.'
complete -c ansible-playbook -l syntax-check --description 'Look for syntax errors in the playbook, but don… [See Man Page]'
complete -c ansible-playbook -l check --description 'Do not make any changes on the remote system, b… [See Man Page]'
complete -c ansible-playbook -l diff --description 'When changing any templated files, show the uni… [See Man Page]'
complete -c ansible-playbook -s T -l timeout --description 'Connection timeout to use when trying to talk t… [See Man Page]'
complete -c ansible-playbook -s s -l sudo --description 'Force all plays to use sudo, even if not marked as such.'
complete -c ansible-playbook -s u -l user --description 'Use this remote user name on playbook steps tha… [See Man Page]'
complete -c ansible-playbook -s c -l connection --description 'Connection type to use.'
complete -c ansible-playbook -s l -l limit --description 'Further limits the selected host/group patterns.'
complete -c ansible-playbook -l list-hosts --description 'Outputs a list of matching hosts; does not exec… [See Man Page]'

