# ansible-pull
# Autogenerated from man page /usr/local/share/man/man1/ansible-pull.1
# using Deroffing man parser
complete -c ansible-pull -s d -l directory --description 'Directory to checkout repository into.'
complete -c ansible-pull -s U -l url --description 'URL of the playbook repository to checkout.'
complete -c ansible-pull -s C -l checkout --description 'Branch/Tag/Commit to checkout.'
complete -c ansible-pull -s f -l force --description 'Force running of playbook even if unable to upd… [See Man Page]'
complete -c ansible-pull -s i -l inventory --description 'The PATH to the inventory hosts file.'
complete -c ansible-pull -l purge --description 'Purge the checkout after the playbook is run.'
complete -c ansible-pull -s m -l module-name --description 'Module used to checkout playbook repository.  Defaults to git.'
complete -c ansible-pull -s o -l only-if-changed --description 'Run the playbook only if the repository has changed.'

