# brew
# Autogenerated from man page /usr/local/share/man/man1/brew.1
# using Deroffing man parser
complete -c brew -l cache: --description '.'
complete -c brew -l cache --description '.'
complete -c brew -l cellar: -l 'prefix)/Cellar' -l 'repository)/Cellar.' --description '.'
complete -c brew -l cellar --description '.'
complete -c brew -l env: --description '.'
complete -c brew -l prefix: --description '.'
complete -c brew -l prefix --description '.'
complete -c brew -l repository: --description '.'
complete -c brew -l version: --description '.'

