# footprint_new
# Autogenerated from man page /usr/share/man/man1/footprint_new.1
# using Darwin man parser
complete -c footprint_new -s a --description 'target all processes (will take much longer).'
complete -c footprint_new -s j --description 'format output in JSON instead of structured text.'
complete -c footprint_new -s t --description 'in addition to the supplied processes, target t… [See Man Page]'
complete -c footprint_new -s s --description 'skip processes that are dirty tracked and have … [See Man Page]'
complete -c footprint_new -s v --description 'display vmmap-like output of address space layout.'
complete -c footprint_new -s h --description 'display help and exit El SAMPLE USAGE Pp footpr… [See Man Page]'

