# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
# using Deroffing man parser
complete -c git-config -l follow-tags --description 'option by default.'
complete -c git-config -l 'no-follow-tags.' --description 'rebase. stat.'

