# git-reflog
# Autogenerated from man page /usr/local/share/man/man1/git-reflog.1
# using Deroffing man parser
complete -c git-reflog -s n -l dry-run --description 'Do not actually prune any entries; just show wh… [See Man Page]'
complete -c git-reflog -l 'expire-unreachable).' --description '.'
complete -c git-reflog -l 'expire).' --description '.'

