# git-rev-list
# Autogenerated from man page /usr/local/share/man/man1/git-rev-list.1
# using Deroffing man parser
complete -c git-rev-list -l invert-grep --description 'Limit the commits output to ones with log messa… [See Man Page]'
complete -c git-rev-list -l 'graph.' --description '.'
complete -c git-rev-list -l 'no-abbrev.' --description 'oc o 2. 3.'

