# git-hash-object
# Autogenerated from man page /usr/local/share/man/man1/git-hash-object.1
# using Deroffing man parser
complete -c git-hash-object -l literally --description 'Allow --stdin to hash any garbage into a loose … [See Man Page]'

