# git-apply
# Autogenerated from man page /usr/local/share/man/man1/git-apply.1
# using Deroffing man parser
complete -c git-apply -l unsafe-paths --description 'By default, a patch that affects outside the wo… [See Man Page]'

