# git-push
# Autogenerated from man page /usr/local/share/man/man1/git-push.1
# using Deroffing man parser
complete -c git-push -l '[no-]atomic' --description 'Use an atomic transaction on the remote side if available.'

