# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
# using Deroffing man parser
complete -c git-log -l invert-grep --description 'Limit the commits output to ones with log messa… [See Man Page]'
complete -c git-log -l 'graph.' --description '.'
complete -c git-log -l 'no-abbrev.' --description 'oc o 2. 3.'

