# git-send-pack
# Autogenerated from man page /usr/local/share/man/man1/git-send-pack.1
# using Deroffing man parser
complete -c git-send-pack -l atomic --description 'Use an atomic transaction for updating the refs.'

